name: Build

on:
  push:

jobs:
  build_app:
    runs-on: windows-latest  # For a list of available runner types, refer to
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      
      - name: List files
        run: ls
      
      # Install the .NET Core workload
      - name: Install .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Build
        run: pwsh -ep bypass ./tools/publish.ps1
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: |
            ./ClassIslandHide/cipx/*
      
      - name: Upload APP to release
        uses: ncipollo/release-action@v1
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          artifacts: "./ClassIslandHide/cipx/*.cipx"
          draft: true
          bodyFile: ./ClassIslandHide/cipx/checksums.md
          token: ${{ secrets.GITHUB_TOKEN }}